#!/bin/bash
wasl-run.pl 2000 400 4046.xls -single -u 0.5 -w 1.0 >> final/uc_0.5/adc_test.txt 
wasl-run.pl 2000 400 4046.xls -single -u 0.5 -w 5.0 >> final/uc_0.5/adc_test.txt 
wasl-run.pl 2000 400 4046.xls -single -u 0.5 -w 10.0 >> final/uc_0.5/adc_test.txt 
wasl-run.pl 2000 400 4046.xls -single -u 0.5 -w 100.0 >> final/uc_0.5/adc_test.txt 
wasl-run.pl 2000 400 4046.xls -single -u 0.5 -w 1000.0 >> final/uc_0.5/adc_test.txt 

wasl-run.pl 8000 400 4046.xls -single -u 0.5 -w 1.0 >> final/default/adc_test.txt 
wasl-run.pl 8000 400 4046.xls -single -u 0.5 -w 5.0 >> final/default/adc_test.txt 
wasl-run.pl 8000 400 4046.xls -single -u 0.5 -w 10.0 >> final/default/adc_test.txt 
wasl-run.pl 8000 400 4046.xls -single -u 0.5 -w 100.0 >> final/default/adc_test.txt 
wasl-run.pl 8000 400 4046.xls -single -u 0.5 -w 1000.0 >> final/default/adc_test.txt 

#wasl-run.pl 2000 400 eventstream.current -single -u 0.5 -w 1.0 >> adc_test.txt 
#wasl-run.pl 2000 400 eventstream.current -single -u 0.5 -w 5.0 >> adc_test.txt 
#wasl-run.pl 2000 400 eventstream.current -single -u 0.5 -w 10.0 >> adc_test.txt 
#wasl-run.pl 2000 400 eventstream.current -single -u 0.5 -w 100.0 >> adc_test.txt 
#wasl-run.pl 2000 400 eventstream.current -single -u 0.5 -w 1000.0 >> adc_test.txt 
#
#wasl-run.pl 2000 100 strace_jaccn.dat -single -u 0.5 -w 1.0 >> adc_test.txt 
#wasl-run.pl 2000 100 strace_jaccn.dat -single -u 0.5 -w 5.0 >> adc_test.txt 
#wasl-run.pl 2000 100 strace_jaccn.dat -single -u 0.5 -w 10.0 >> adc_test.txt 
#wasl-run.pl 2000 100 strace_jaccn.dat -single -u 0.5 -w 100.0 >> adc_test.txt 
#wasl-run.pl 2000 100 strace_jaccn.dat -single -u 0.5 -w 1000.0 >> adc_test.txt 
#
#wasl-run.pl 8000 1600 messages.sdb -single -u 0.5 -w 1.0 >> adc_test.txt 
#wasl-run.pl 8000 1600 messages.sdb -single -u 0.5 -w 5.0 >> adc_test.txt 
#wasl-run.pl 8000 1600 messages.sdb -single -u 0.5 -w 10.0 >> adc_test.txt 
#wasl-run.pl 8000 1600 messages.sdb -single -u 0.5 -w 100.0 >> adc_test.txt 
#wasl-run.pl 8000 1600 messages.sdb -single -u 0.5 -w 1000.0 >> adc_test.txt 
#
#wasl-run.pl 8000 100 HALO_have2impression.log.1 -single -u 0.5 -w 1.0 >> adc_test.txt 
#wasl-run.pl 8000 100 HALO_have2impression.log.1 -single -u 0.5 -w 5.0 >> adc_test.txt 
#wasl-run.pl 8000 100 HALO_have2impression.log.1 -single -u 0.5 -w 10.0 >> adc_test.txt 
#wasl-run.pl 8000 100 HALO_have2impression.log.1 -single -u 0.5 -w 100.0 >> adc_test.txt 
#wasl-run.pl 8000 100 HALO_have2impression.log.1 -single -u 0.5 -w 1000.0 >> adc_test.txt 
