#!/bin/bash
# runs tests using random data
# edit args to coltest to change type of test
I=12000
while [ $I -le 15000	 ]
do
coltest $I 10 0 > trial.txt 2> scratch.sml
#cat scratch.sml
sml -m sources-new.cm scratch.sml
((I=I+1000))
done
