:PACKAGE: ast

.SOURCE : .. ../include

CCFLAGS = $(CC.DEBUG) $(CC.DLL)

padsc 1.0 :LIBRARY: rbuf.c libpadsc-acc-gen.c libpadsc-read-gen.c libpadsc-gen.c

$(INCLUDEDIR) :INSTALLPROTO: libpadsc.h libpadsc-internal.h rbuf.h
