:PACKAGE: ast

.SOURCE : .. ../include

CCFLAGS = $(CC.DEBUG) $(CC.DLL)

padsc 1.0 :LIBRARY: libpadsc.c libpadsc-accum.c libpadsc-gen.c rbuf.c

$(INCLUDEDIR) :INSTALLPROTO: libpadsc.h libpadsc-internal.h rbuf.h
