#!/usr/bin/env perl

$ifilename = $ARGV[0];
open(IFILE, $ifilename) || die "Could not open input file $ifilename\n";

$defgen = 0;
top: while (<IFILE>) {
  s/\#gen_include/\#include/g;
  if (/DEFGEN\((.*)\)/) {
    $defgenfile = $1;
    open(DFILE, ">tmp1.$defgenfile") || die "could not open tmp1.$defgenfile\n";
    $defgen = 1;
    if ($defgenfile =~ /[.]h$/) {
      print DFILE "#pragma prototyped\n";
    }
    print DFILE "/*\n * WARNING: GENERATED FILE.  Do not edit this file, edit $ifilename instead. \n */\n\n";
    next;
  }
  if (/BEGIN_MACGEN\((.*)\)/) {
    $mgenfile = $1;
    open(MGFILE, ">tmp1.$mgenfile") || die "could not open tmp1.$mgenfile\n";
    print MGFILE "#pragma prototyped\n";
    print MGFILE "/*\n * WARNING: GENERATED FILE.  Do not edit this file, edit $ifilename instead. \n */\n\n";
    open(MGTMPFILE, ">tmp2.$mgenfile") || die "could not open tmp2.$mgenfile\n";
    while (<IFILE>) {
      s/\#gen_include/\#include/g;
      if (/END_HEADER/) {
	goto end_macgen_header;
      }
      print MGFILE;
    }
    die "END_HEADER not found while building $mgenfile";
  end_macgen_header:
    close(MGFILE);
    while (<IFILE>) {
      s/\#gen_include/\#include/g;
      if (/BEGIN_TRAILER/) {
	goto begin_macgen_trailer;
      }
      print MGTMPFILE;
    }
    die "BEGIN_TRAILER not found while building $mgenfile";
  begin_macgen_trailer:
    close(MGTMPFILE);
    $cmd = "cc -E tmp2.$mgenfile | ./addnl.pl | cat >> tmp1.$mgenfile 2>&1";
    $res = `$cmd`;
    if ($res =~ /ERROR/) {
      die "Error running command $cmd\n";
    }
    open(MGFILE, ">>tmp1.$mgenfile") || die "could not open tmp1.$mgenfile\n";
    while (<IFILE>) {
      s/\#gen_include/\#include/g;
      if (/END_MACGEN/) {
	goto end_macgen;
      }
      print MGFILE;
    }
    die "END_MACGEN not found while building $mgenfile";
  end_macgen:
    close(MGFILE);
    $cmd = "cat tmp1.$mgenfile | stripnlnl.pl | cat > $mgenfile";
    $res = `$cmd`;
    if ($res =~ /ERROR/) {
      die "Error running command $cmd\n";
    }
    next top;
  }
  if (/BEGIN_MACROS\((.*)\)/) {
    $macfile = $1;
    $defname = uc($macfile);
    $defname =~ s/\-/_/g;
    $defname =~ s/\./_/g;
    $defname = "__$defname"."__";
    open(MFILE, ">tmp1.$macfile") || die "could not open tmp1.$macfile\n";
    print MFILE "#pragma prototyped\n";
    print MFILE "/*\n * WARNING: GENERATED FILE.  Do not edit this file, edit $ifilename instead. \n */\n\n";
    print MFILE "#ifndef $defname\n#define $defname\n\n";
    while (<IFILE>) {
      s/\#gen_include/\#include/g;
      if (/END_HEADER/) {
	goto end_mac_header;
      }
      print MFILE;
    }
    die "END_HEADER not found while building $macfile";
  end_mac_header:
    $seen_define = 0;
    while (<IFILE>) {
      s/\#gen_include/\#include/g;
      if (/BEGIN_TRAILER/) {
	goto begin_mac_trailer;
      }
      chomp;
      if (/\#define/) {
	print MFILE "\n\n$_ \\\n";
	$seen_define = 1;
      } elsif (/END_MACRO/) {
	$seen_define = 0;
      } elsif ($seen_define) {
	print MFILE "$_ \\\n";
      } else {
	print MFILE "$_\n";
      }
    }
    die "BEGIN_TRAILER not found while building $macfile";
  begin_mac_trailer:
    print MFILE "\n\n";
    while (<IFILE>) {
      s/\#gen_include/\#include/g;
      if (/END_MACROS/) {
	goto end_mac;
      }
      print MFILE;
    }
    die "END_MACROS not found while building $macfile";
  end_mac:
    print MFILE "\n#endif  /*  $defname  */\n\n";
    close(MFILE);
    $cmd = "cat tmp1.$macfile | stripnlnl.pl | cat > $macfile";
    $res = `$cmd`;
    if ($res =~ /ERROR/) {
      die "Error running command $cmd\n";
    }
    next top;
  }
  if ($defgen == 1) {
    print DFILE;
  } else {
    if (/\#\#/) {
      # comment line at the top -- do nothing
    } else {
      chomp;
      if (length($_) > 0) {
	print "Warning: DEFGEN not specified, so this line has no home:\n$_\n";
      }
    }
  }
  next top;
}
if ($defgen == 1) {
  close(DFILE);
  $cmd = "cat tmp1.$defgenfile | stripnlnl.pl | cat > $defgenfile";
  $res = `$cmd`;
  if ($res =~ /ERROR/) {
    die "Error running command $cmd\n";
  }
}
$cmd = "/bin/rm -f tmp[12].*";
$res = `$cmd`;
if ($res =~ /ERROR/) {
  die "Error running command $cmd\n";
}
