######################################################################
# This is a GNU makefile
######################################################################

######################################################################
#
# Infrastructure to produce test output
#
######################################################################
maxdepth-simplegroups = 50

%::
	cd ..; ./learn data/$@ -d output/$@ `maxdepth.pl $@`
	touch $@

1967Transactions.short:  ../data/1967Transactions.short
MER_T01_01.csv:          ../data/MER_T01_01.csv
ProfSec.log:             ../data/ProfSec.log
SCESETUP.LOG:            ../data/SCESETUP.LOG
access_log:              ../data/access_log
ai-simple:               ../data/ai-simple
ai.3000:                 ../data/ai.3000
apache.txt:              ../data/apache.txt
asl.log:                 ../data/asl.log
backup1.log:             ../data/backup1.log
backup2.log:             ../data/backup2.log
boot.log:                ../data/boot.log
crashreporter.log:       ../data/crashreporter.log
daily.out:               ../data/daily.out
dibbler.1000:            ../data/dibbler.1000
dmesg:                   ../data/dmesg
error_log:               ../data/error_log
hp-array:                ../data/hp-array
hp-struct:               ../data/hp-struct
ijnltif:                 ../data/ijnltif
install.log:             ../data/install.log
interactions.txt.small:  ../data/interactions.txt.small
interface.loop:          ../data/interface.loop
lsof:                    ../data/lsof
netstat:                 ../data/netstat
netstat-an:              ../data/netstat-an
page_log:                ../data/page_log
quarterlypersonalincome: ../data/quarterlypersonalincome
railroad.txt:            ../data/railroad.txt
rpmpkgs:                 ../data/rpmpkgs
scesetup2.log:           ../data/scesetup2.log
scrollkeeper.log:        ../data/scrollkeeper.log
simplegroups:            ../data/simplegroups
simplexml:               ../data/simplexml
windowserver_last.log:   ../data/windowserver_last.log
yum.log:                 ../data/yum.log
yum.txt:                 ../data/yum.txt
