:PACKAGE: ast

.SOURCE : .. ../../../include

if 0
CCFLAGS = $(CC.OPTIMIZE)
end
CCFLAGS = $(CC.DEBUG)

myrand :: myrand.c
cvt_ebcdic_to_ascii :: cvt_ebcdic_to_ascii.c
cvt_ascii_to_ebcdic :: cvt_ascii_to_ebcdic.c


libtests : ebcdic_test adate_test mk_ex_data_libtest2 mk_ex_data_ebcdic_test libtest1 libtest2 ebcdic_libtest4 libtest4 rbuftest1 mk_ex_data_biglibtest1 biglibtest1 string_share_test

accumtests : accumtest accumtest2 accumtest_s

alltests : libtests accumtests

adate_test       :: adate_test.c        -lpadsc
libtest1         :: libtest1.c          -lpadsc
biglibtest1      :: biglibtest1.c       -lpadsc
libtest2         :: libtest2.c          -lpadsc
libtest4         :: libtest4.c          -lpadsc
ebcdic_libtest4  :: ebcdic_libtest4.c   -lpadsc
rbuftest1        :: rbuftest1.c         -lpadsc
ebcdic_test      :: ebcdic_test.c       -lpadsc

dttest         :: dttest.c        -lpadsc
accumtest      :: accumtest.c     -lpadsc
accumtest2     :: accumtest2.c    -lpadsc
accumtest_s    :: accumtest_s.c   -lpadsc

string_share_test   :: string_share_test.c          -lpadsc

mk_ex_data_biglibtest1 :: mk_ex_data_biglibtest1.c
mk_ex_data_libtest2    :: mk_ex_data_libtest2.c
mk_ex_data_ebcdic_test :: mk_ex_data_ebcdic_test.c

regress : regress_libtest1 \
          regress_libtest2 \
          regress_libtest4 \
          regress_ebcdic_test \
          regress_ebcdic_libtest4

regress_libtest1 : libtest1
	if [ -f tmp/tmp.libtest1 ]; then $(RM) tmp/tmp.libtest1; fi
	(./libtest1 nlrec_noseek 2>&1) | grep -v XXX_REMOVE | cat > tmp/tmp.libtest1
	diff tmp/tmp.libtest1 ../../regress/libtest1.regress || echo LIBTEST1 DIFFERS

regress_libtest2 : libtest2
	if [ -f tmp/tmp.libtest2 ]; then $(RM) tmp/tmp.libtest2; fi
	(./libtest2 2>&1) | grep -v XXX_REMOVE | grep -v 'fname = ' | cat > tmp/tmp.libtest2
	diff tmp/tmp.libtest2 ../../regress/libtest2.regress || echo LIBTEST2 DIFFERS

regress_libtest4 : libtest4
	if [ -f tmp/tmp.libtest4 ]; then $(RM) tmp/tmp.libtest4; fi
	(./libtest4 2>&1) | grep -v XXX_REMOVE | cat > tmp/tmp.libtest4
	diff tmp/tmp.libtest4 ../../regress/libtest4.regress || echo LIBTEST4 DIFFERS

regress_ebcdic_libtest4 : ebcdic_libtest4
	if [ -f tmp/tmp.ebcdic_libtest4 ]; then $(RM) tmp/tmp.ebcdic_libtest4; fi
	(./ebcdic_libtest4 2>&1) | grep -v XXX_REMOVE | cat > tmp/tmp.ebcdic_libtest4
	diff tmp/tmp.ebcdic_libtest4 ../../regress/ebcdic_libtest4.regress || echo EBCDIC_LIBTEST4 DIFFERS

regress_ebcdic_test : ebcdic_test
	if [ -f tmp/tmp.ebcdic_test ]; then $(RM) tmp/tmp.ebcdic_test; fi
	(./ebcdic_test ctrec_noseek 2>&1) | grep -v XXX_REMOVE | cat > tmp/tmp.ebcdic_test
	diff tmp/tmp.ebcdic_test ../../regress/ebcdic_test.regress || echo EBCDIC_TEST DIFFERS

clean :
	$(RM) -f *.o *test* *~

veryclean : clean
	$(RM) -f Makefile.ms Makefile.mo padsc.req

