:PACKAGE: ast

.SOURCE : .. ../../../include

if 0
CCFLAGS = $(CC.OPTIMIZE)
end
CCFLAGS = $(CC.DEBUG)

myrand :: myrand.c

libtests : mk_ex_data_libtest2 libtest1 libtest2 libtest4 rbuftest1 mk_ex_data_biglibtest1 biglibtest1 string_share_test

accumtests : accumtest accumtest2 accumtest_s

alltests : libtests accumtests

libtest1         :: libtest1.c          -lpadsc
biglibtest1      :: biglibtest1.c       -lpadsc
libtest2         :: libtest2.c          -lpadsc
libtest4         :: libtest4.c          -lpadsc
rbuftest1        :: rbuftest1.c         -lpadsc

dttest         :: dttest.c        -lpadsc
accumtest      :: accumtest.c     -lpadsc
accumtest2     :: accumtest2.c    -lpadsc
accumtest_s    :: accumtest_s.c   -lpadsc

string_share_test   :: string_share_test.c          -lpadsc

mk_ex_data_biglibtest1 :: mk_ex_data_biglibtest1.c
mk_ex_data_libtest2    :: mk_ex_data_libtest2.c

regress : regress_libtest1 \
          regress_libtest2 \
          regress_libtest4

regress_libtest1 : libtest1
	if [ -f tmp/tmp.libtest1 ]; then $(RM) tmp/tmp.libtest1; fi
	(./libtest1 nlrec_noseek 2>&1) | grep -v XXX_REMOVE | cat > tmp/tmp.libtest1
	diff tmp/tmp.libtest1 ../../regress/libtest1.regress || echo LIBTEST1 DIFFERS

regress_libtest2 : libtest2
	if [ -f tmp/tmp.libtest2 ]; then $(RM) tmp/tmp.libtest2; fi
	(./libtest2 2>&1) | grep -v XXX_REMOVE | cat > tmp/tmp.libtest2
	diff tmp/tmp.libtest2 ../../regress/libtest2.regress || echo LIBTEST2 DIFFERS

regress_libtest4 : libtest4
	if [ -f tmp/tmp.libtest4 ]; then $(RM) tmp/tmp.libtest4; fi
	(./libtest4 2>&1) | grep -v XXX_REMOVE | cat > tmp/tmp.libtest4
	diff tmp/tmp.libtest4 ../../regress/libtest4.regress || echo LIBTEST4 DIFFERS

clean :
	$(RM) -f *.o *test* *~

veryclean : clean
	$(RM) -f Makefile.ms Makefile.mo padsc.req

