#!/bin/sh
#will be filled in by install script

_arch_n_opsys=`$PADS_HOME/scripts/arch-n-opsys`

SMLBIN=$PADS_HOME/binlinks/smlruntime.$_arch_n_opsys
IMAGE=$PADS_HOME/documents/extract-code/extract-code
 
exec $SMLBIN @SMLload=$IMAGE $* < /dev/null
