#!/bin/bash
# Run the accumulator program, defending against error return
# $1 is the name of the data file
echo "Data file = " $1;
if gen/darwin.ppc/$1-accum data/$1 2>gen/$1-accum.out
then echo "Accumulator program succeeded"
else echo "Accumulator program failed"
fi
exit 0
