:PACKAGE: ast

.SOURCE : ../include

CCFLAGS = $(CC.DEBUG)

test_format1 :: test_format1.c format1.c -lpadsc
test_format3 :: test_format3.c format3.c -lpadsc

libtest1 :: libtest1.c -lpadsc
rbuftest1 :: rbuftest1.c -lpadsc
