:PACKAGE: ast

.SOURCE : ../include

CCFLAGS = $(CC.DEBUG)

if 0
test_format1 :: test_format1.c format1.c -lpadsc
end
test_format1 :: test_format1.c format1.c -lpadsc

test_format2 :: test_format2.c -lpadsc

