#include "vanilla.p"
Ptypedef Pstring_ME(:"/[A-Za-z0-9_ ]+/":) subject_t;
Ptypedef Pstring_SE(:"/\\\t/":) any_t;

Precord Pstruct header_t {
        subject_t       v_h_spot;
        '\t';
        subject_t       v_h_name;
        '\t';
        subject_t       v_h_clone_id;
        '\t';
        subject_t       v_h_gene_sym;
        '\t';
        subject_t       v_h_gene_name;
        '\t';
        subject_t       v_h_cluster_id;
        '\t';
        subject_t       v_h_accession;
        '\t';
        subject_t       v_h_pref_name;
        '\t';
        subject_t       v_h_suid;
        '\t';
        subject_t       v_h_ch1i_mean;
        '\t';
        subject_t       v_h_ch1d_median;
        '\t';
        subject_t       v_h_ch1i_median;
        '\t';
        subject_t       v_h_ch1_per_sat;
        '\t';
        subject_t       v_h_ch1i_sd;
        '\t';
        subject_t       v_h_ch1b_mean;
        '\t';
        subject_t       v_h_ch1b_median;
        '\t';
        subject_t       v_h_ch1b_sd;
        '\t';
        subject_t       v_h_ch1d_mean;
        '\t';
        subject_t       v_h_ch2i_mean;
        '\t';
        subject_t       v_h_ch2d_mean;
        '\t';
        subject_t       v_h_ch2d_median;
        '\t';
        subject_t       v_h_ch2i_median;
        '\t';
        subject_t       v_h_ch2_per_sat;
        '\t';
        subject_t       v_h_ch2i_sd;
        '\t';
        subject_t       v_h_ch2b_mean;
        '\t';
        subject_t       v_h_ch2b_median;
        '\t';
        subject_t       v_h_ch2b_sd;
        '\t';
        subject_t       v_h_ch2bn_median;
        '\t';
        subject_t       v_h_ch2dn_mean;
        '\t';
        subject_t       v_h_ch2in_mean;
        '\t';
        subject_t       v_h_ch2dn_median;
        '\t';
        subject_t       v_h_ch2in_median;
        '\t';
        subject_t       v_h_corr;
        '\t';
        subject_t       v_h_diameter;
        '\t';
        subject_t       v_h_flag;
        '\t';
        subject_t       v_h_log_rat2n_mean;
        '\t';
        subject_t       v_h_log_rat2n_median;
        '\t';
        subject_t       v_h_pix_rat2_mean;
        '\t';
        subject_t       v_h_pix_rat2_median;
        '\t';
        subject_t       v_h_pergtbch1i_1sd;
        '\t';
        subject_t       v_h_pergtbch1i_2sd;
        '\t';
        subject_t       v_h_pergtbch2i_1sd;
        '\t';
        subject_t       v_h_pergtbch2i_2sd;
        '\t';
        subject_t       v_h_rat1_mean;
        '\t';
        subject_t       v_h_rat1n_mean;
        '\t';
        subject_t       v_h_rat2_mean;
        '\t';
        subject_t       v_h_rat2_median;
        '\t';
        subject_t       v_h_rat2_sd;
        '\t';
        subject_t       v_h_rat2n_mean;
        '\t';
        subject_t       v_h_rat2n_median;
        '\t';
        subject_t       v_h_regr;
        '\t';
        subject_t       v_h_sum_mean;
        '\t';
        subject_t       v_h_sum_median;
        '\t';
        subject_t       v_h_tot_bpix;
        '\t';
        subject_t       v_h_tot_spix;
        '\t';
        subject_t       v_h_x_coord;
        '\t';
        subject_t       v_h_y_coord;
        '\t';
        subject_t       v_h_top;
        '\t';
        subject_t       v_h_bot;
        '\t';
        subject_t       v_h_left;
        '\t';
        subject_t       v_h_right;
        '\t';
        subject_t       v_h_sector;
        '\t';
        subject_t       v_h_sectorrow;
        '\t';
        subject_t       v_h_sectorcol;
        '\t';
        subject_t       v_h_source;
        '\t';
        subject_t       v_h_plateid;
        '\t';
        subject_t       v_h_prow;
        '\t';
        subject_t       v_h_pcol;
        '\t';
        subject_t       v_h_failed;
        '\t';
        subject_t       v_h_isver;
        '\t';
        subject_t       v_h_is_cont;
        '\t';
        subject_t       v_h_luid;
}

Precord Pstruct entry_t {
        Puint32         v_spot;
        '\t';
        any_t           v_name;
        '\t';
        any_t           v_clone_id;
        '\t';
        any_t           v_gene_sym;
        '\t';
        any_t           v_gene_name;
        '\t';
        any_t       v_cluster_id;
        '\t';
        any_t           v_accession;
        '\t';
        any_t       v_pref_name;
        '\t';
        Popt Puint32       v_suid;
        '\t';
        any_t       v_ch1i_mean;
        '\t';
        any_t       v_ch1d_median;
        '\t';
        any_t       v_ch1i_median;
        '\t';
        any_t       v_ch1_per_sat;
        '\t';
        any_t       v_ch1i_sd;
        '\t';
        any_t       v_ch1b_mean;
        '\t';
        any_t       v_ch1b_median;
        '\t';
        any_t       v_ch1b_sd;
        '\t';
        any_t       v_ch1d_mean;
        '\t';
        any_t       v_ch2i_mean;
        '\t';
        any_t       v_ch2d_mean;
        '\t';
        any_t       v_ch2d_median;
        '\t';
        any_t       v_ch2i_median;
        '\t';
        any_t       v_ch2_per_sat;
        '\t';
        any_t       v_ch2i_sd;
        '\t';
        any_t       v_ch2b_mean;
        '\t';
        any_t       v_ch2b_median;
        '\t';
        any_t       v_ch2b_sd;
        '\t';
        any_t       v_ch2bn_median;
        '\t';
        any_t       v_ch2dn_mean;
        '\t';
        any_t       v_ch2in_mean;
        '\t';
        any_t       v_ch2dn_median;
        '\t';
        any_t       v_ch2in_median;
        '\t';
        any_t       v_corr;
        '\t';
        any_t       v_diameter;
        '\t';
        any_t       v_flag;
        '\t';
        any_t       v_log_rat2n_mean;
        '\t';
        any_t       v_log_rat2n_median;
        '\t';
        any_t       v_pix_rat2_mean;
        '\t';
        any_t       v_pix_rat2_median;
        '\t';
        any_t       v_pergtbch1i_1sd;
        '\t';
        any_t       v_pergtbch1i_2sd;
        '\t';
        any_t       v_pergtbch2i_1sd;
        '\t';
        any_t       v_pergtbch2i_2sd;
        '\t';
        any_t       v_rat1_mean;
        '\t';
        any_t       v_rat1n_mean;
        '\t';
        any_t       v_rat2_mean;
        '\t';
        any_t       v_rat2_median;
        '\t';
        any_t       v_rat2_sd;
        '\t';
        any_t       v_rat2n_mean;
        '\t';
        any_t       v_rat2n_median;
        '\t';
        any_t       v_regr;
        '\t';
        any_t       v_sum_mean;
        '\t';
        any_t       v_sum_median;
        '\t';
        any_t       v_tot_bpix;
        '\t';
        any_t       v_tot_spix;
        '\t';
        any_t       v_x_coord;
        '\t';
        any_t       v_y_coord;
        '\t';
        any_t       v_top;
        '\t';
        any_t       v_bot;
        '\t';
        any_t       v_left;
        '\t';
        any_t       v_right;
        '\t';
        any_t       v_sector;
        '\t';
        any_t       v_sectorrow;
        '\t';
        any_t       v_sectorcol;
        '\t';
        any_t       v_source;
        '\t';
        any_t       v_plateid;
        '\t';
        Popt PPstring       v_prow;
        '\t';
        Popt Puint32    v_pcol;
        '\t';
        Popt Puint32    v_failed;
        '\t';
        Popt PPstring    v_isver;
        '\t';
        Popt PPstring   v_is_cont;
        '\t';
        Popt Puint32       v_luid;
};

Punion table_entry_t {
        header_t v_header;
        entry_t  v_entry;
};

Psource Parray table_t {
	table_entry_t[];
};
