import "padsc.idl";

Perror_t iPint32_read    ([in,ptr] P_t *pads, [out,ref] Pbase_pd *pd, [out,ref] Pint32 *res_out);
Perror_t iPuint32_read   ([in,ptr] P_t *pads, [out,ref] Pbase_pd *pd, [out,ref] Puint32 *res_out);

Perror_t iPint32_FW_read ([in,ptr] P_t *pads, [out,ref] Pbase_pd *pd, [out,ref] Pint32 *res_out, [in] size_t width);
Perror_t iPuint32_FW_read ([in,ptr] P_t *pads, [out,ref] Pbase_pd *pd, [out,ref] Puint32 *res_out, [in] size_t width);

